### ISSUE TITLE
Change (again) how the path and base_path are calcuated

### ISSUE THREAD

**Issue by pcg79** [petems/riot_api#10]
Just discovered that in the v2.1 API the difference in URLs isn't just changing the version, they also removed an entire path level.  /sigh.  I'll redo this today.

![riot games api 2013-12-12 11-33-13](https://f.cloud.github.com/assets/10041/1734779/68e81420-634b-11e3-8cae-f82e125d12bb.jpg)

**Comment by petems** [comment]
Fixed in #11
