### ISSUE TITLE
Implement all existing end points

### ISSUE THREAD

**Issue by pcg79** [petems/riot_api#15]
This is just to track end point progress for my own sanity.

Champion 1.1:
- [x] champion (freeToPlay = false)
- [x] champion (freeToPlay = true)

Game 1.1:
- [x] recent 

League 2.1:
- [x] by-summoner

Stats 1.1:
- [x] summary
- [x] summary (allow specify season)
- [x] ranked
- [x] ranked (allow specify season)

Summoner 1.1:
- [x] masteries
- [x] runes
- [x] by-name (may need to change method name as to not conflict with name by_ids)
- [x] summoner (by_id)
- [x] name (by_ids)

Team 2.1:
- [x] by-summoner

**Comment by petems** [comment]
:+1:

**Comment by pcg79** [comment]
Once you finish the Team methods, we're good to go here.

**Comment by petems** [comment]
All implemented :+1:

**Comment by pcg79** [comment]
If you're happy w/ my PRs from yesterday either go ahead and pull them or just give them your blessing (a :+1: will do :)) and I'll pull them and we can get the next version of the gem deployed.

**Comment by petems** [comment]
Cool, yeah they all look good, let me just have a last looksie and you can merge.

Also, have you had experience with testing STDOUT in Ruby before? If so, could you have at the test I added in #26 ? Not sure the best way to do it...

**Comment by pcg79** [comment]
Awesome.  All merged. I think we're good to release the next version of the gem and then work on models.
