### ISSUE TITLE
Can't get Champions list

### ISSUE THREAD

**Issue by JDiPierro** [petems/riot_api#24]
I've got a riot_api client with:
client = RiotApi::API.new :api_key => 'APIKEY', :region => 'na', :debug => true

It is working as I can do:
@me = client.summoner.name('FerretWithASpork')

and then print out me.name, but when I try:
@champions = client.champions.list()

I get:
undefined method `champions' for #RiotApi::API:0x1dcd1c8

**Comment by JDiPierro** [comment]
Disregard. The version on Rubygems isn't the most up to date.. looks like it only has Summoner and Stats? Any ETA on when you'll be releasing the rest to rubygems?

**Comment by petems** [comment]
Good point, forgot to release the latest changes! Will push that now :+1:

**Comment by petems** [comment]
Released in `0.0.3` :smile:

**Comment by JDiPierro** [comment]
You rock! Thanks!

**Comment by pcg79** [comment]
fyi, I removed your api key from the issue.

**Comment by petems** [comment]
Good catch, that's why I did #26, forgot to remove it here!

Unlikely that anyone saw it, but you might want to regenerate it @JDiPierro! :smile:
