### ISSUE TITLE
Handle api errors gracefully

### ISSUE THREAD

**Issue by pcg79** [petems/riot_api#34]
Right now if a user passes in a wrong season (to `stats`) the Riot app returns a 404 in html which the JSON parser can't parse causing an exception.  I also believe there are other instances of web pages being returned.

We need to handle this better.

**Comment by petems** [comment]
This should be handled by the @raise_status_errors parameter, which uses the Faraday status error middleware. 

However, it appears the json middleware jumps in before the error can be raised...

Let me a have a look

**Comment by petems** [comment]
Ok, easy-peasy fix it turns out after hacking away for an hour on a custom error handler :sweat_smile:

PR for the change here: https://github.com/petems/riot_api/pull/36

**Comment by petems** [comment]
Fixed in https://github.com/petems/riot_api/commit/53022de8464652949e553cc7054eab183275bb04
