### ISSUE TITLE
Implement classes instead of using Hashie

### ISSUE THREAD

**Issue by pcg79** [petems/riot_api#7]
I think at some point actual classes for the returned endpoints will need to be implemented instead of using Hashie.  So, as a contrived example, if Riot implements a GET id endpoint for champions with the current implementation of the API one would have to do something like:

`ra.champions.get( ra.games.recent.first.champion_id )`

With classes you'd be able to do

`ra.games.recent.first.champion`

which would do the GET for you.

Classes we'll need:

Game:
- [x] Game
- [x] Player
- [x] Statistic

League:
- [x] League
- [x] LeagueEntry

Champions:
- [x] Champion

Stats:
- [x] Champion (different from above but above should work fine)
- [x] Stat

Summoner:
- [x] Summoner
- [x] MasteryPage
- [x] Talent
- [x] RunePage
- [x] Slot (implemented as Rune class)
- [x] Rune

Team:
- [x] Team
- [x] Match
- [x] Roster
- [x] MemberList
- [x] TeamId
- [x] TeamStatSummary
- [x] TeamStatDetail
- [ ] MessageOfTheDay - According to the API this is one of the classes that's returned but I dont' actually see it in any of our data.  I don't think it needs to be implemented just yet.

**Comment by petems** [comment]
That would be cool :+1:

**Comment by petems** [comment]
Shouldn't be too hard:

``` ruby
require 'riot_api'
require 'virtus'

ra = RiotApi::API.new :api_key => ENV['RIOT_API_KEY'], :region => 'euw'

summoner_details = ra.summoner.name('BestLuxEUW')

puts summoner_details

class Summoner
  include Virtus.model

  attribute :id,        Integer
  attribute :name,      String
  attribute :profileIconId, Integer
  attribute :summonerLevel, Integer
  attribute :revisionDateStr, String
end

summoner = Summoner.new(summoner_details)

puts "Summoner Name is: #{summoner.name}" # => "Summoner Name is: Best Lux EUW"
```

**Comment by pcg79** [comment]
Wow, that's a lot easier than I remember.

I need to get some work done (the kind I get paid for :)) so if you don't beat me to it, I'll see about doing this tonight/tomorrow morning (east coast US time).

**Comment by petems** [comment]
Cool beans! :+1:

**Comment by petems** [comment]
Ok current plan: implement all the endpoints, release it as 0.0.3.

Then class it up, release that as 0.1.0 :+1: 

I've made you a collab. Just open any pull requests you want before merging for discussion, unless it's a trivial change like a typo or something then go nuts and commit to master :smile:

**Comment by pcg79** [comment]
Sounds good.  Tomorrow I'll implement w/e endpoints we're missing.  Looks like we have 7 or so of the 11 or so total.

Not sure I'll get to work on this any over the weekend, fyi.

**Comment by petems** [comment]
Yeah, I was doing some of the larger endpoints like Team last night... You end up with a lot of data in a hashie with no real meaning to it. But I'd rather we at least implement all the endpoints then class them up :+1:

**Comment by pcg79** [comment]
Assuming you're working on Team I'll do the rest of summoner and stats today.  We should probably come to a consensus on a pattern for method names.

Probably not surprising I'm a Rails developer so I'm used to methods like `find_by...`.  While I don't think we need to use that pattern, we may want to at least use something like `by_id`, `by_name`, etc.  As I implement more endpoints today I'll see if I can come up w/ something that makes sense and run it by you.

Also, b/c I can't keep it all straight in my head, I made an issue to track end point completion - https://github.com/petems/riot_api/issues/15

**Comment by petems** [comment]
`by_fieldname` seems good to me :+1: 

Most of my Ruby and Rails experience is in support and scripting, so I'll defer to your class and architecture knowledge :smiley:

**Comment by pcg79** [comment]
I edited my original post to list the classes I think we'll need.  I think we're just about there.  Should be able to wrap that up in the next day or two and release a new version of the gem.

**Comment by pcg79** [comment]
Ok, once the two PRs (#40 and #41) are pulled we're good here and can release a new version of them.

@petems Check em out real quick and we're good.

**Comment by pcg79** [comment]
Doh, I totally forgot about team.  @petems are you still implementing that or should I go ahead and do it?  I edited the class list above with the classes it looks like we'll need for that call.

**Comment by pcg79** [comment]
Ok, with #42 _now_ I think we're good.
